### ISSUE TITLE
TypeError: Cannot read property 'realpath' of undefined

### ISSUE THREAD

**Issue by activescott** [micromatch/glob-fs#9]
I get the below when using `readdirPromise`:
    /Users/scott/Dropbox/Docs/Scripts/mail-restore-js/node_modules/glob-fs/lib/symlinks.js:38
            self.realpath(file, cb);
                ^

```
TypeError: Cannot read property 'realpath' of undefined
    at /Users/scott/Dropbox/Docs/Scripts/mail-restore-js/node_modules/glob-fs/lib/symlinks.js:38:15
    at LOOP (fs.js:1609:14)
    at _combinedTickCallback (node.js:376:9)
    at process._tickCallback (node.js:407:11)
```

**Comment by tunnckoCore** [comment]
Not so surprising for me, haha. Try to not use it yet, it's very basic and raw. Or if you just play, thanks for the report ;] 
We are coming to it soon. :)
